name: Deploy to EC2

on:
  push:
    branches: [ "feat_add_ec2_redis" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Sync code to EC2
        run: |
          rsync -avz --delete --exclude node_modules --exclude .git ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_PATH }}

      - name: Write .env on remote
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cat > ${{ secrets.EC2_PATH }}/apps/socket-server/.env << ENV_EOF
PORT=${{ secrets.PORT }}
NODE_ENV=production
CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}
REDIS_URL=${{ secrets.REDIS_URL }}
ENV_EOF
          EOF

      - name: Remote install & restart via pm2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e
          cd ${{ secrets.EC2_PATH }}/apps/socket-server
          npm ci --production
          pm2 start ./ecosystem.config.js --env production || pm2 reload ecosystem.config.js --env production
          pm2 save
          EOF
